name = "UKBBEpistasisPipeline"
uuid = "878921ef-e6e1-4b21-a067-0762adcb6c43"
authors = ["Olivier Labayle"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
