name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/julia-buildpkg@v1
      # - uses: julia-actions/julia-docdeploy@v1
      #   with:
      #     install-package: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GitHubActions.jl in its own (shared) environment
        run: |
          using Pkg
          Pkg.activate("docs-logger-env"; shared=true)
          Pkg.add(Pkg.PackageSpec(name="GitHubActions", version="0.1"))
        shell: julia --color=yes {0}
      - run: |
          # The Julia command that will be executed
          julia_cmd=( julia --color=yes --project=docs/ -e '
              @eval Module() begin
                  push!(LOAD_PATH, "@docs-logger-env") # access GitHubActions.jl
                  import Logging, GitHubActions
                  Logging.global_logger(GitHubActions.GitHubActionsLogger())
                  pop!(LOAD_PATH)
              end
              include("docs/make.jl")' )
          # Run the Julia command
          "${julia_cmd[@]}"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
