name: CI
on:
  - push
  - pull_request
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Test ${{ matrix.testrun }} -- ${{ github.event_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testrun:
          - "from_actors.jl"
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: nf-core/setup-nextflow@v1.2.0
      - name: Instantiate test environment
        run: julia --project=test --startup-file=no -e'using Pkg;Pkg.instantiate()'
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Run tests
        run: julia --project=test --startup-file=no test/${{ matrix.testrun }} -profile ci